# Generated by Django 5.2.3 on 2025-06-22 05:24

import content.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("question", "Question"),
                            ("note", "Study Note"),
                            ("material", "Study Material"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("image", "Image"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=content.models.content_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "docx",
                                    "txt",
                                    "jpg",
                                    "png",
                                    "jpeg",
                                    "mp4",
                                    "avi",
                                    "mov",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "semester",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=200)),
                (
                    "keywords",
                    models.TextField(
                        blank=True, help_text="Comma-separated keywords for search"
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "content",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Content Categories",
                "db_table": "content_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentDownload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
            ],
            options={
                "db_table": "content_downloads",
            },
        ),
        migrations.CreateModel(
            name="ContentRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "content_ratings",
            },
        ),
        migrations.CreateModel(
            name="ContentView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "content_views",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("short_answer", "Short Answer"),
                            ("long_answer", "Long Answer"),
                            ("numerical", "Numerical"),
                            ("true_false", "True/False"),
                        ],
                        max_length=20,
                    ),
                ),
                ("option_a", models.TextField(blank=True)),
                ("option_b", models.TextField(blank=True)),
                ("option_c", models.TextField(blank=True)),
                ("option_d", models.TextField(blank=True)),
                ("correct_answer", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("marks", models.PositiveIntegerField(default=1)),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("exam_type", models.CharField(blank=True, max_length=100)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("correct_attempt_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_content", models.TextField()),
                ("summary", models.TextField(blank=True)),
                (
                    "estimated_read_time",
                    models.PositiveIntegerField(
                        help_text="Estimated reading time in minutes"
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True, help_text="External references and citations"
                    ),
                ),
            ],
            options={
                "db_table": "study_materials",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#007bff", max_length=7)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserBookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "user_bookmarks",
            },
        ),
    ]
