# Generated by Django 5.2.3 on 2025-06-22 05:24

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("question_answer", "Question & Answer"),
                            ("explanation", "Explanation"),
                            ("problem_solving", "Problem Solving"),
                            ("study_plan", "Study Plan Generation"),
                            ("content_summary", "Content Summary"),
                            ("image_analysis", "Image Analysis"),
                        ],
                        max_length=30,
                    ),
                ),
                ("user_input", models.TextField()),
                ("input_context", models.JSONField(default=dict)),
                ("ai_response", models.TextField()),
                ("ai_model", models.CharField(max_length=50)),
                ("response_metadata", models.JSONField(default=dict)),
                ("response_time_ms", models.PositiveIntegerField()),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "user_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_interactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModelUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("total_response_time_ms", models.PositiveBigIntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("average_confidence", models.FloatField(default=0.0)),
                ("average_user_rating", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_model_usage",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("ai", "AI Response"),
                            ("system", "System Message"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_format",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("code", "Code"),
                            ("math", "Mathematical Expression"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_attachments/"
                    ),
                ),
                ("ai_model", models.CharField(blank=True, max_length=50)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("references", models.JSONField(blank=True, default=list)),
                (
                    "user_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("session_data", models.JSONField(blank=True, default=dict)),
                ("total_messages", models.PositiveIntegerField(default=0)),
                ("total_tokens_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "chat_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("exam_prep", "Exam Preparation"),
                            ("topic_mastery", "Topic Mastery"),
                            ("revision", "Revision Plan"),
                            ("custom", "Custom Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("topics", models.JSONField(default=list)),
                ("goals", models.JSONField(default=dict)),
                ("schedule", models.JSONField(default=dict)),
                ("total_tasks", models.PositiveIntegerField(default=0)),
                ("completed_tasks", models.PositiveIntegerField(default=0)),
                ("ai_generated", models.BooleanField(default=True)),
                ("generation_params", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "study_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyPlanTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("read", "Reading"),
                            ("practice", "Practice Questions"),
                            ("video", "Watch Video"),
                            ("review", "Review Notes"),
                            ("assignment", "Assignment"),
                            ("quiz", "Quiz"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        help_text="Estimated duration in minutes"
                    ),
                ),
                (
                    "actual_duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Actual time spent in minutes"
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "study_plan_tasks",
                "ordering": ["scheduled_date", "order"],
            },
        ),
    ]
