# Generated by Django 5.2.3 on 2025-06-22 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AItutor", "0001_initial"),
        ("content", "0001_initial"),
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinteraction",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="student.course",
            ),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aimodelusage",
            unique_together={("model_name", "date")},
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="related_content",
            field=models.ManyToManyField(
                blank=True, related_name="referenced_in_chat", to="content.content"
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="student.course",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="AItutor.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AItutor.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="courses",
            field=models.ManyToManyField(
                related_name="study_plans", to="student.course"
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studyplantask",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.content",
            ),
        ),
        migrations.AddField(
            model_name="studyplantask",
            name="study_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="AItutor.studyplan",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["user", "interaction_type"],
                name="ai_interact_user_id_b9dec6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["ai_model", "created_at"], name="ai_interact_ai_mode_2e29a8_idx"
            ),
        ),
    ]
