# Generated by Django 5.2.3 on 2025-06-22 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AItutor", "0002_initial"),
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("fill_blank", "Fill in the Blank"),
                            ("matching", "Matching"),
                            ("numerical", "Numerical Answer"),
                            ("code", "Code/Programming"),
                        ],
                        max_length=20,
                    ),
                ),
                ("correct_answer", models.TextField()),
                ("answer_options", models.JSONField(blank=True, default=dict)),
                ("answer_explanation", models.TextField(blank=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_score",
                    models.FloatField(
                        default=0.0, help_text="AI-calculated difficulty (0-1)"
                    ),
                ),
                (
                    "estimated_solve_time",
                    models.PositiveIntegerField(
                        default=60, help_text="Estimated solve time in seconds"
                    ),
                ),
                ("actual_solve_times", models.JSONField(blank=True, default=list)),
                ("topics", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ai_generated", "AI Generated"),
                            ("user_uploaded", "User Uploaded"),
                            ("admin_created", "Admin Created"),
                            ("web_scraped", "Web Scraped"),
                            ("past_exam", "Past Exam Question"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("source_reference", models.CharField(blank=True, max_length=500)),
                (
                    "question_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="question_images/"
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="OCR extracted text from image"
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("correct_answers_count", models.PositiveIntegerField(default=0)),
                ("total_attempts", models.PositiveIntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("is_verified", models.BooleanField(default=False)),
                ("question_embedding", models.JSONField(blank=True, default=list)),
                ("answer_embedding", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="student.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PastQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exam_year", models.PositiveIntegerField()),
                ("exam_semester", models.CharField(blank=True, max_length=20)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("midterm", "Midterm Exam"),
                            ("final", "Final Exam"),
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("practice", "Practice Test"),
                            ("certification", "Certification Exam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("exam_name", models.CharField(max_length=255)),
                ("institution", models.CharField(blank=True, max_length=255)),
                ("instructor", models.CharField(blank=True, max_length=255)),
                ("question_number", models.CharField(blank=True, max_length=10)),
                ("total_marks", models.PositiveIntegerField(default=1)),
                ("section", models.CharField(blank=True, max_length=100)),
                (
                    "original_document",
                    models.FileField(blank=True, null=True, upload_to="past_exams/"),
                ),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_past_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_question_info",
                        to="AItutor.question",
                    ),
                ),
            ],
            options={
                "db_table": "past_questions",
                "ordering": ["-exam_year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("question_embedding", models.JSONField(default=list)),
                ("answer_embedding", models.JSONField(default=list)),
                ("combined_embedding", models.JSONField(default=list)),
                (
                    "embedding_model",
                    models.CharField(default="text-embedding-3-small", max_length=50),
                ),
                ("embedding_dimensions", models.PositiveIntegerField(default=1536)),
                ("similarity_matches", models.PositiveIntegerField(default=0)),
                ("used_for_generation", models.PositiveIntegerField(default=0)),
                ("source_quality_score", models.FloatField(default=0.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_entries",
                        to="AItutor.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_bank",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("practice", "Practice Quiz"),
                            ("mock_exam", "Mock Exam"),
                            ("topic_review", "Topic Review"),
                            ("difficulty_test", "Difficulty Assessment"),
                            ("past_questions", "Past Questions Quiz"),
                            ("mixed", "Mixed Content"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("topics", models.JSONField(default=list)),
                ("difficulty_range", models.JSONField(default=dict)),
                ("question_types", models.JSONField(default=list)),
                ("total_questions", models.PositiveIntegerField(default=10)),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Time limit in minutes", null=True
                    ),
                ),
                ("generation_params", models.JSONField(default=dict)),
                ("ai_generated", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("access_code", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="student.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("points", models.PositiveIntegerField(default=1)),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time limit for this question in seconds",
                        null=True,
                    ),
                ),
                ("is_bonus", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AItutor.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AItutor.quiz"
                    ),
                ),
            ],
            options={
                "db_table": "quiz_questions",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                related_name="quizzes",
                through="AItutor.QuizQuestion",
                to="AItutor.question",
            ),
        ),
        migrations.CreateModel(
            name="UserQuizSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                            ("paused", "Paused"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("answers", models.JSONField(default=dict)),
                ("answer_times", models.JSONField(default=dict)),
                ("current_question", models.PositiveIntegerField(default=1)),
                ("score", models.FloatField(default=0.0)),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                (
                    "total_time_spent",
                    models.PositiveIntegerField(
                        default=0, help_text="Total time in seconds"
                    ),
                ),
                ("difficulty_performance", models.JSONField(default=dict)),
                ("topic_performance", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to="AItutor.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_quiz_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["course", "difficulty_level"],
                name="ai_question_course__b2313b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type", "source_type"],
                name="ai_question_questio_96f220_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty_score", "average_rating"],
                name="ai_question_difficu_043565_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pastquestion",
            index=models.Index(
                fields=["exam_year", "exam_type"], name="past_questi_exam_ye_351264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pastquestion",
            index=models.Index(
                fields=["exam_year", "is_verified"],
                name="past_questi_exam_ye_293e09_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["content_hash"], name="question_ba_content_c26da0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["source_quality_score"], name="question_ba_source__786f58_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizquestion",
            unique_together={("quiz", "question")},
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["course", "quiz_type"], name="quizzes_course__6fce0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["status", "is_public"], name="quizzes_status_ac46df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userquizsession",
            index=models.Index(
                fields=["user", "status"], name="user_quiz_s_user_id_97662b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userquizsession",
            index=models.Index(
                fields=["quiz", "completed_at"], name="user_quiz_s_quiz_id_a0a266_idx"
            ),
        ),
    ]
