# Generated by Django 5.2.3 on 2025-06-22 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AItutor",
            "0003_question_pastquestion_questionbank_quiz_quizquestion_and_more",
        ),
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("educational_website", "Educational Website"),
                            ("question_bank", "Online Question Bank"),
                            ("textbook_site", "Textbook Website"),
                            ("university_site", "University Website"),
                            ("certification_site", "Certification Website"),
                            ("practice_platform", "Practice Platform"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "domains",
                    models.JSONField(default=list, help_text="Subject domains covered"),
                ),
                (
                    "languages",
                    models.JSONField(default=list, help_text="Languages supported"),
                ),
                (
                    "question_types",
                    models.JSONField(
                        default=list, help_text="Types of questions available"
                    ),
                ),
                (
                    "quality_rating",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reliability_score",
                    models.FloatField(
                        default=0.0, help_text="AI-assessed reliability (0-1)"
                    ),
                ),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                ("scrape_frequency_hours", models.PositiveIntegerField(default=24)),
                ("requires_authentication", models.BooleanField(default=False)),
                ("api_key_required", models.BooleanField(default=False)),
                ("rate_limit_per_hour", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "online_sources",
                "ordering": ["-quality_rating", "-reliability_score"],
            },
        ),
        migrations.CreateModel(
            name="DifficultyAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conceptual_complexity",
                    models.FloatField(
                        default=0.0, help_text="Conceptual understanding required (0-1)"
                    ),
                ),
                (
                    "computational_complexity",
                    models.FloatField(
                        default=0.0, help_text="Computational steps required (0-1)"
                    ),
                ),
                (
                    "cognitive_load",
                    models.FloatField(
                        default=0.0, help_text="Mental processing load (0-1)"
                    ),
                ),
                (
                    "prerequisite_knowledge",
                    models.JSONField(
                        default=list, help_text="Required prerequisite concepts"
                    ),
                ),
                (
                    "estimated_read_time",
                    models.PositiveIntegerField(
                        default=30, help_text="Time to read question (seconds)"
                    ),
                ),
                (
                    "estimated_think_time",
                    models.PositiveIntegerField(
                        default=60, help_text="Time to understand/plan (seconds)"
                    ),
                ),
                (
                    "estimated_solve_time",
                    models.PositiveIntegerField(
                        default=120, help_text="Time to solve (seconds)"
                    ),
                ),
                (
                    "estimated_review_time",
                    models.PositiveIntegerField(
                        default=30, help_text="Time to review answer (seconds)"
                    ),
                ),
                (
                    "actual_solve_times",
                    models.JSONField(
                        default=list, help_text="User solve times in seconds"
                    ),
                ),
                (
                    "success_rates_by_skill",
                    models.JSONField(
                        default=dict, help_text="Success rates by user skill level"
                    ),
                ),
                (
                    "common_mistakes",
                    models.JSONField(
                        default=list, help_text="Common wrong answers/mistakes"
                    ),
                ),
                (
                    "analysis_model",
                    models.CharField(default="gemini-pro", max_length=50),
                ),
                ("analysis_confidence", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_analysis",
                        to="AItutor.question",
                    ),
                ),
            ],
            options={
                "db_table": "difficulty_analyses",
            },
        ),
        migrations.CreateModel(
            name="QuizCustomization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("default_num_questions", models.PositiveIntegerField(default=10)),
                (
                    "default_difficulty",
                    models.CharField(default="intermediate", max_length=20),
                ),
                (
                    "default_time_limit",
                    models.PositiveIntegerField(
                        default=30, help_text="Default time limit in minutes"
                    ),
                ),
                ("preferred_topics", models.JSONField(default=list)),
                ("preferred_question_types", models.JSONField(default=list)),
                ("adaptive_difficulty", models.BooleanField(default=True)),
                ("difficulty_adjustment_rate", models.FloatField(default=0.1)),
                ("include_past_questions", models.BooleanField(default=True)),
                ("include_ai_generated", models.BooleanField(default=True)),
                ("include_user_uploaded", models.BooleanField(default=True)),
                ("past_questions_weight", models.FloatField(default=0.4)),
                ("ai_generated_weight", models.FloatField(default=0.4)),
                ("user_uploaded_weight", models.FloatField(default=0.2)),
                ("track_performance", models.BooleanField(default=True)),
                ("show_analytics", models.BooleanField(default=True)),
                ("get_recommendations", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_courses",
                    models.ManyToManyField(blank=True, to="student.course"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quiz_customizations",
            },
        ),
        migrations.CreateModel(
            name="EmbeddingVector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("question_answer", "Question + Answer"),
                            ("question_only", "Question Only"),
                            ("answer_only", "Answer Only"),
                            ("explanation", "Explanation"),
                            ("topic_summary", "Topic Summary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vector_data",
                    models.JSONField(help_text="Embedding vector as JSON array"),
                ),
                (
                    "vector_model",
                    models.CharField(default="text-embedding-3-small", max_length=50),
                ),
                ("vector_dimension", models.PositiveIntegerField(default=1536)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("is_cached", models.BooleanField(default=True)),
                ("similarity_threshold", models.FloatField(default=0.8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="AItutor.question",
                    ),
                ),
            ],
            options={
                "db_table": "embedding_vectors",
                "indexes": [
                    models.Index(
                        fields=["content_hash"], name="embedding_v_content_24e7a0_idx"
                    ),
                    models.Index(
                        fields=["vector_model", "content_type"],
                        name="embedding_v_vector__181150_idx",
                    ),
                ],
                "unique_together": {("question", "content_type")},
            },
        ),
        migrations.CreateModel(
            name="UserPerformanceAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("semester", "Semester"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_questions_attempted", models.PositiveIntegerField(default=0)),
                ("total_questions_correct", models.PositiveIntegerField(default=0)),
                ("total_time_spent_minutes", models.PositiveIntegerField(default=0)),
                (
                    "topic_performance",
                    models.JSONField(default=dict, help_text="Performance by topic"),
                ),
                (
                    "difficulty_performance",
                    models.JSONField(
                        default=dict, help_text="Performance by difficulty"
                    ),
                ),
                (
                    "question_type_performance",
                    models.JSONField(
                        default=dict, help_text="Performance by question type"
                    ),
                ),
                ("improvement_rate", models.FloatField(default=0.0)),
                ("consistency_score", models.FloatField(default=0.0)),
                ("learning_velocity", models.FloatField(default=0.0)),
                ("weak_topics", models.JSONField(default=list)),
                ("strong_topics", models.JSONField(default=list)),
                ("suggested_focus_areas", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_analytics",
                        to="student.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_performance_analytics",
                "ordering": ["-period_end"],
                "unique_together": {("user", "course", "period_start", "period_type")},
            },
        ),
    ]
