# Generated by Django 5.2.3 on 2025-06-22 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AItutor", "0004_onlinesource_difficultyanalysis_quizcustomization_and_more"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="student.course",
            ),
        ),
    ]
